package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func main() {
	branch := gitOutput("rev-parse", "--abbrev-ref", "HEAD")
	sha := gitOutput("rev-parse", "--short", "HEAD")

	ver := branch + "-" + sha
	if build := os.Getenv("BUILD_NUMBER"); build != "" {
		ver += "-" + build
	}

	content := fmt.Sprintf(`package version

// Version is the application version. Generated by go run ./cmd/version.
var Version = %q
`, ver)

	if err := os.WriteFile("internal/version/version.go", []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing version file: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(ver)
}

func gitOutput(args ...string) string {
	out, err := exec.Command("git", args...).Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, "git %s: %v\n", strings.Join(args, " "), err)
		os.Exit(1)
	}
	return strings.TrimSpace(string(out))
}
