// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"
	"database/sql"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, name, token_hash, created_by)
VALUES (?, ?, ?, ?)
`

type CreateDeviceParams struct {
	ID        string
	Name      string
	TokenHash string
	CreatedBy string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedBy,
	)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, name, token_hash, created_by, created_at, last_seen_at, revoked_at
FROM devices
WHERE id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
SELECT id, name, token_hash, created_by, created_at, last_seen_at, revoked_at
FROM devices
WHERE token_hash = ?
`

func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, token_hash, created_by, created_at, last_seen_at, revoked_at
FROM devices
ORDER BY created_at
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE devices SET revoked_at = datetime('now') WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeDevice, id)
	return err
}

const rotateDeviceToken = `-- name: RotateDeviceToken :execresult
UPDATE devices
   SET token_hash = ?
 WHERE id = ?
   AND revoked_at IS NULL
`

type RotateDeviceTokenParams struct {
	TokenHash string
	ID        string
}

func (q *Queries) RotateDeviceToken(ctx context.Context, arg RotateDeviceTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rotateDeviceToken, arg.TokenHash, arg.ID)
}

const touchDeviceSeen = `-- name: TouchDeviceSeen :execresult
UPDATE devices
   SET last_seen_at = datetime('now')
 WHERE id = ?
   AND (last_seen_at IS NULL OR last_seen_at < datetime('now', ?))
`

type TouchDeviceSeenParams struct {
	ID       string
	Datetime interface{}
}

func (q *Queries) TouchDeviceSeen(ctx context.Context, arg TouchDeviceSeenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, touchDeviceSeen, arg.ID, arg.Datetime)
}
