// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package db

import (
	"context"
)

const createInvitation = `-- name: CreateInvitation :exec
INSERT INTO invitations (id, email, role, invited_by)
VALUES (?, ?, ?, ?)
`

type CreateInvitationParams struct {
	ID        string
	Email     string
	Role      string
	InvitedBy string
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) error {
	_, err := q.db.ExecContext(ctx, createInvitation,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = ?
`

func (q *Queries) DeleteInvitation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvitation, id)
	return err
}

const deleteInvitationByEmail = `-- name: DeleteInvitationByEmail :exec
DELETE FROM invitations WHERE email = ?
`

func (q *Queries) DeleteInvitationByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteInvitationByEmail, email)
	return err
}

const getInvitationByEmail = `-- name: GetInvitationByEmail :one
SELECT id, email, role, invited_by, created_at
FROM invitations
WHERE email = ?
`

func (q *Queries) GetInvitationByEmail(ctx context.Context, email string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByEmail, email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, email, role, invited_by, created_at
FROM invitations
WHERE id = ?
`

func (q *Queries) GetInvitationByID(ctx context.Context, id string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, email, role, invited_by, created_at
FROM invitations
ORDER BY created_at
`

func (q *Queries) ListInvitations(ctx context.Context) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
