// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Device struct {
	ID         string
	Name       string
	TokenHash  string
	CreatedBy  string
	CreatedAt  string
	LastSeenAt sql.NullString
	RevokedAt  sql.NullString
}

type Invitation struct {
	ID        string
	Email     string
	Role      string
	InvitedBy string
	CreatedAt string
}

type Session struct {
	TokenHash string
	UserID    string
	CsrfToken string
	CreatedAt string
	ExpiresAt string
}

type User struct {
	ID          string
	Email       string
	DisplayName string
	Role        string
	Active      int64
	CreatedAt   string
	UpdatedAt   string
}
