// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Device struct {
	ID         string
	Name       string
	TokenHash  string
	CreatedBy  string
	CreatedAt  string
	LastSeenAt sql.NullString
	RevokedAt  sql.NullString
	ScreenID   sql.NullString
}

type Invitation struct {
	ID        string
	Email     string
	Role      string
	InvitedBy string
	CreatedAt string
}

type Page struct {
	ID        string
	ScreenID  string
	Name      string
	Position  int64
	CreatedAt string
	UpdatedAt string
}

type Screen struct {
	ID                      string
	Name                    string
	ThemeID                 string
	RotationIntervalSeconds int64
	CreatedAt               string
	UpdatedAt               string
}

type Session struct {
	TokenHash string
	UserID    string
	CsrfToken string
	CreatedAt string
	ExpiresAt string
}

type Theme struct {
	ID             string
	Name           string
	IsDefault      int64
	ColorBg        string
	ColorSurface   string
	ColorBorder    string
	ColorText      string
	ColorTextMuted string
	ColorAccent    string
	FontFamily     string
	FontFamilyMono string
	Radius         string
	CreatedAt      string
	UpdatedAt      string
}

type User struct {
	ID          string
	Email       string
	DisplayName string
	Role        string
	Active      int64
	CreatedAt   string
	UpdatedAt   string
}

type WidgetInstance struct {
	ID        string
	PageID    string
	Type      string
	Config    string
	Position  int64
	CreatedAt string
	UpdatedAt string
}
