// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package db

import (
	"context"
	"database/sql"
)

const createPage = `-- name: CreatePage :exec
INSERT INTO pages (id, screen_id, name, position)
VALUES (?, ?, ?, ?)
`

type CreatePageParams struct {
	ID       string
	ScreenID string
	Name     string
	Position int64
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.ExecContext(ctx, createPage,
		arg.ID,
		arg.ScreenID,
		arg.Name,
		arg.Position,
	)
	return err
}

const deletePage = `-- name: DeletePage :execresult
DELETE FROM pages WHERE id = ? AND screen_id = ?
`

type DeletePageParams struct {
	ID       string
	ScreenID string
}

func (q *Queries) DeletePage(ctx context.Context, arg DeletePageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePage, arg.ID, arg.ScreenID)
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, screen_id, name, position, created_at, updated_at
FROM pages
WHERE id = ? AND screen_id = ?
`

type GetPageByIDParams struct {
	ID       string
	ScreenID string
}

func (q *Queries) GetPageByID(ctx context.Context, arg GetPageByIDParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageByID, arg.ID, arg.ScreenID)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.ScreenID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageNeighbor = `-- name: GetPageNeighbor :one
SELECT id, screen_id, name, position, created_at, updated_at
FROM pages
WHERE screen_id = ? AND position = ?
`

type GetPageNeighborParams struct {
	ScreenID string
	Position int64
}

func (q *Queries) GetPageNeighbor(ctx context.Context, arg GetPageNeighborParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageNeighbor, arg.ScreenID, arg.Position)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.ScreenID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPagesByScreen = `-- name: ListPagesByScreen :many
SELECT id, screen_id, name, position, created_at, updated_at
FROM pages
WHERE screen_id = ?
ORDER BY position
`

func (q *Queries) ListPagesByScreen(ctx context.Context, screenID string) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPagesByScreen, screenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.ScreenID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxPagePosition = `-- name: MaxPagePosition :one
SELECT COALESCE(MAX(position), 0) FROM pages WHERE screen_id = ?
`

func (q *Queries) MaxPagePosition(ctx context.Context, screenID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxPagePosition, screenID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const setPagePosition = `-- name: SetPagePosition :exec
UPDATE pages SET position = ?, updated_at = datetime('now')
WHERE id = ? AND screen_id = ?
`

type SetPagePositionParams struct {
	Position int64
	ID       string
	ScreenID string
}

func (q *Queries) SetPagePosition(ctx context.Context, arg SetPagePositionParams) error {
	_, err := q.db.ExecContext(ctx, setPagePosition, arg.Position, arg.ID, arg.ScreenID)
	return err
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages SET name = ?, updated_at = datetime('now')
WHERE id = ? AND screen_id = ?
`

type UpdatePageParams struct {
	Name     string
	ID       string
	ScreenID string
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.ExecContext(ctx, updatePage, arg.Name, arg.ID, arg.ScreenID)
	return err
}
