// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: screens.sql

package db

import (
	"context"
	"database/sql"
)

const countScreensUsingTheme = `-- name: CountScreensUsingTheme :one
SELECT COUNT(*) FROM screens WHERE theme_id = ?
`

func (q *Queries) CountScreensUsingTheme(ctx context.Context, themeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScreensUsingTheme, themeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScreen = `-- name: CreateScreen :exec
INSERT INTO screens (id, name, theme_id, rotation_interval_seconds)
VALUES (?, ?, ?, ?)
`

type CreateScreenParams struct {
	ID                      string
	Name                    string
	ThemeID                 string
	RotationIntervalSeconds int64
}

func (q *Queries) CreateScreen(ctx context.Context, arg CreateScreenParams) error {
	_, err := q.db.ExecContext(ctx, createScreen,
		arg.ID,
		arg.Name,
		arg.ThemeID,
		arg.RotationIntervalSeconds,
	)
	return err
}

const deleteScreen = `-- name: DeleteScreen :execresult
DELETE FROM screens WHERE id = ?
`

func (q *Queries) DeleteScreen(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteScreen, id)
}

const getScreenByID = `-- name: GetScreenByID :one
SELECT id, name, theme_id, rotation_interval_seconds, created_at, updated_at
FROM screens
WHERE id = ?
`

func (q *Queries) GetScreenByID(ctx context.Context, id string) (Screen, error) {
	row := q.db.QueryRowContext(ctx, getScreenByID, id)
	var i Screen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ThemeID,
		&i.RotationIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScreenByName = `-- name: GetScreenByName :one
SELECT id, name, theme_id, rotation_interval_seconds, created_at, updated_at
FROM screens
WHERE name = ?
`

func (q *Queries) GetScreenByName(ctx context.Context, name string) (Screen, error) {
	row := q.db.QueryRowContext(ctx, getScreenByName, name)
	var i Screen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ThemeID,
		&i.RotationIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScreenSummaries = `-- name: ListScreenSummaries :many
SELECT
    s.id,
    s.name,
    s.theme_id,
    s.rotation_interval_seconds,
    s.created_at,
    s.updated_at,
    t.name AS theme_name,
    (SELECT COUNT(*) FROM pages p WHERE p.screen_id = s.id) AS page_count
FROM screens s
JOIN themes t ON t.id = s.theme_id
ORDER BY s.name
`

type ListScreenSummariesRow struct {
	ID                      string
	Name                    string
	ThemeID                 string
	RotationIntervalSeconds int64
	CreatedAt               string
	UpdatedAt               string
	ThemeName               string
	PageCount               int64
}

func (q *Queries) ListScreenSummaries(ctx context.Context) ([]ListScreenSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listScreenSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScreenSummariesRow
	for rows.Next() {
		var i ListScreenSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ThemeID,
			&i.RotationIntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThemeName,
			&i.PageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScreens = `-- name: ListScreens :many
SELECT id, name, theme_id, rotation_interval_seconds, created_at, updated_at
FROM screens
ORDER BY name
`

func (q *Queries) ListScreens(ctx context.Context) ([]Screen, error) {
	rows, err := q.db.QueryContext(ctx, listScreens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screen
	for rows.Next() {
		var i Screen
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ThemeID,
			&i.RotationIntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScreen = `-- name: UpdateScreen :exec
UPDATE screens
   SET name = ?,
       theme_id = ?,
       rotation_interval_seconds = ?,
       updated_at = datetime('now')
 WHERE id = ?
`

type UpdateScreenParams struct {
	Name                    string
	ThemeID                 string
	RotationIntervalSeconds int64
	ID                      string
}

func (q *Queries) UpdateScreen(ctx context.Context, arg UpdateScreenParams) error {
	_, err := q.db.ExecContext(ctx, updateScreen,
		arg.Name,
		arg.ThemeID,
		arg.RotationIntervalSeconds,
		arg.ID,
	)
	return err
}
