// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: themes.sql

package db

import (
	"context"
	"database/sql"
)

const clearDefaultTheme = `-- name: ClearDefaultTheme :exec
UPDATE themes SET is_default = 0 WHERE is_default = 1
`

func (q *Queries) ClearDefaultTheme(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultTheme)
	return err
}

const countDefaultThemes = `-- name: CountDefaultThemes :one
SELECT COUNT(*) FROM themes WHERE is_default = 1
`

func (q *Queries) CountDefaultThemes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDefaultThemes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTheme = `-- name: CreateTheme :exec
INSERT INTO themes (
    id, name, is_default,
    color_bg, color_surface, color_border, color_text, color_text_muted, color_accent,
    font_family, font_family_mono, radius
) VALUES (
    ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?
)
`

type CreateThemeParams struct {
	ID             string
	Name           string
	IsDefault      int64
	ColorBg        string
	ColorSurface   string
	ColorBorder    string
	ColorText      string
	ColorTextMuted string
	ColorAccent    string
	FontFamily     string
	FontFamilyMono string
	Radius         string
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) error {
	_, err := q.db.ExecContext(ctx, createTheme,
		arg.ID,
		arg.Name,
		arg.IsDefault,
		arg.ColorBg,
		arg.ColorSurface,
		arg.ColorBorder,
		arg.ColorText,
		arg.ColorTextMuted,
		arg.ColorAccent,
		arg.FontFamily,
		arg.FontFamilyMono,
		arg.Radius,
	)
	return err
}

const deleteTheme = `-- name: DeleteTheme :execresult
DELETE FROM themes WHERE id = ? AND is_default = 0
`

func (q *Queries) DeleteTheme(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTheme, id)
}

const getDefaultTheme = `-- name: GetDefaultTheme :one
SELECT id, name, is_default, color_bg, color_surface, color_border, color_text, color_text_muted, color_accent, font_family, font_family_mono, radius, created_at, updated_at
FROM themes
WHERE is_default = 1
LIMIT 1
`

func (q *Queries) GetDefaultTheme(ctx context.Context) (Theme, error) {
	row := q.db.QueryRowContext(ctx, getDefaultTheme)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.ColorBg,
		&i.ColorSurface,
		&i.ColorBorder,
		&i.ColorText,
		&i.ColorTextMuted,
		&i.ColorAccent,
		&i.FontFamily,
		&i.FontFamilyMono,
		&i.Radius,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThemeByID = `-- name: GetThemeByID :one
SELECT id, name, is_default, color_bg, color_surface, color_border, color_text, color_text_muted, color_accent, font_family, font_family_mono, radius, created_at, updated_at
FROM themes
WHERE id = ?
`

func (q *Queries) GetThemeByID(ctx context.Context, id string) (Theme, error) {
	row := q.db.QueryRowContext(ctx, getThemeByID, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.ColorBg,
		&i.ColorSurface,
		&i.ColorBorder,
		&i.ColorText,
		&i.ColorTextMuted,
		&i.ColorAccent,
		&i.FontFamily,
		&i.FontFamilyMono,
		&i.Radius,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThemeByName = `-- name: GetThemeByName :one
SELECT id, name, is_default, color_bg, color_surface, color_border, color_text, color_text_muted, color_accent, font_family, font_family_mono, radius, created_at, updated_at
FROM themes
WHERE name = ?
`

func (q *Queries) GetThemeByName(ctx context.Context, name string) (Theme, error) {
	row := q.db.QueryRowContext(ctx, getThemeByName, name)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.ColorBg,
		&i.ColorSurface,
		&i.ColorBorder,
		&i.ColorText,
		&i.ColorTextMuted,
		&i.ColorAccent,
		&i.FontFamily,
		&i.FontFamilyMono,
		&i.Radius,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listThemes = `-- name: ListThemes :many
SELECT id, name, is_default, color_bg, color_surface, color_border, color_text, color_text_muted, color_accent, font_family, font_family_mono, radius, created_at, updated_at
FROM themes
ORDER BY name
`

func (q *Queries) ListThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.QueryContext(ctx, listThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.ColorBg,
			&i.ColorSurface,
			&i.ColorBorder,
			&i.ColorText,
			&i.ColorTextMuted,
			&i.ColorAccent,
			&i.FontFamily,
			&i.FontFamilyMono,
			&i.Radius,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultTheme = `-- name: SetDefaultTheme :execresult
UPDATE themes SET is_default = 1 WHERE id = ?
`

func (q *Queries) SetDefaultTheme(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, setDefaultTheme, id)
}

const updateTheme = `-- name: UpdateTheme :exec
UPDATE themes
   SET name = ?,
       color_bg = ?, color_surface = ?, color_border = ?,
       color_text = ?, color_text_muted = ?, color_accent = ?,
       font_family = ?, font_family_mono = ?, radius = ?,
       updated_at = datetime('now')
 WHERE id = ?
`

type UpdateThemeParams struct {
	Name           string
	ColorBg        string
	ColorSurface   string
	ColorBorder    string
	ColorText      string
	ColorTextMuted string
	ColorAccent    string
	FontFamily     string
	FontFamilyMono string
	Radius         string
	ID             string
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) error {
	_, err := q.db.ExecContext(ctx, updateTheme,
		arg.Name,
		arg.ColorBg,
		arg.ColorSurface,
		arg.ColorBorder,
		arg.ColorText,
		arg.ColorTextMuted,
		arg.ColorAccent,
		arg.FontFamily,
		arg.FontFamilyMono,
		arg.Radius,
		arg.ID,
	)
	return err
}
