// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: widget_instances.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createWidgetInstance = `-- name: CreateWidgetInstance :exec
INSERT INTO widget_instances (id, page_id, type, config, position)
VALUES (?, ?, ?, ?, ?)
`

type CreateWidgetInstanceParams struct {
	ID       string
	PageID   string
	Type     string
	Config   string
	Position int64
}

func (q *Queries) CreateWidgetInstance(ctx context.Context, arg CreateWidgetInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createWidgetInstance,
		arg.ID,
		arg.PageID,
		arg.Type,
		arg.Config,
		arg.Position,
	)
	return err
}

const deleteWidgetInstance = `-- name: DeleteWidgetInstance :execresult
DELETE FROM widget_instances WHERE id = ? AND page_id = ?
`

type DeleteWidgetInstanceParams struct {
	ID     string
	PageID string
}

func (q *Queries) DeleteWidgetInstance(ctx context.Context, arg DeleteWidgetInstanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteWidgetInstance, arg.ID, arg.PageID)
}

const getWidgetInstanceByID = `-- name: GetWidgetInstanceByID :one
SELECT id, page_id, type, config, position, created_at, updated_at
FROM widget_instances
WHERE id = ? AND page_id = ?
`

type GetWidgetInstanceByIDParams struct {
	ID     string
	PageID string
}

func (q *Queries) GetWidgetInstanceByID(ctx context.Context, arg GetWidgetInstanceByIDParams) (WidgetInstance, error) {
	row := q.db.QueryRowContext(ctx, getWidgetInstanceByID, arg.ID, arg.PageID)
	var i WidgetInstance
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Type,
		&i.Config,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWidgetNeighbor = `-- name: GetWidgetNeighbor :one
SELECT id, page_id, type, config, position, created_at, updated_at
FROM widget_instances
WHERE page_id = ? AND position = ?
`

type GetWidgetNeighborParams struct {
	PageID   string
	Position int64
}

func (q *Queries) GetWidgetNeighbor(ctx context.Context, arg GetWidgetNeighborParams) (WidgetInstance, error) {
	row := q.db.QueryRowContext(ctx, getWidgetNeighbor, arg.PageID, arg.Position)
	var i WidgetInstance
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Type,
		&i.Config,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWidgetInstancesByPage = `-- name: ListWidgetInstancesByPage :many
SELECT id, page_id, type, config, position, created_at, updated_at
FROM widget_instances
WHERE page_id = ?
ORDER BY position
`

func (q *Queries) ListWidgetInstancesByPage(ctx context.Context, pageID string) ([]WidgetInstance, error) {
	rows, err := q.db.QueryContext(ctx, listWidgetInstancesByPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WidgetInstance
	for rows.Next() {
		var i WidgetInstance
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Type,
			&i.Config,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetInstancesByPageIDs = `-- name: ListWidgetInstancesByPageIDs :many
SELECT id, page_id, type, config, position, created_at, updated_at
FROM widget_instances
WHERE page_id IN (/*SLICE:page_ids*/?)
ORDER BY page_id, position
`

func (q *Queries) ListWidgetInstancesByPageIDs(ctx context.Context, pageIds []string) ([]WidgetInstance, error) {
	query := listWidgetInstancesByPageIDs
	var queryParams []interface{}
	if len(pageIds) > 0 {
		for _, v := range pageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:page_ids*/?", strings.Repeat(",?", len(pageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:page_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WidgetInstance
	for rows.Next() {
		var i WidgetInstance
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Type,
			&i.Config,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxWidgetPosition = `-- name: MaxWidgetPosition :one
SELECT CAST(COALESCE(MAX(position), 0) AS INTEGER) FROM widget_instances WHERE page_id = ?
`

func (q *Queries) MaxWidgetPosition(ctx context.Context, pageID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxWidgetPosition, pageID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setWidgetPosition = `-- name: SetWidgetPosition :exec
UPDATE widget_instances SET position = ?, updated_at = datetime('now')
WHERE id = ? AND page_id = ?
`

type SetWidgetPositionParams struct {
	Position int64
	ID       string
	PageID   string
}

func (q *Queries) SetWidgetPosition(ctx context.Context, arg SetWidgetPositionParams) error {
	_, err := q.db.ExecContext(ctx, setWidgetPosition, arg.Position, arg.ID, arg.PageID)
	return err
}
